name: New Grad Role
description: Contribute a new grad position to our list
title: "New Grad"
labels: ["new_grad"]
body:
  - type: markdown
    attributes:
      value: |
        ## New Grad Contribution Form
        Thanks for taking the time to contribute!
        > Make sure you've read `CONTRIBUTING.md` before submitting your grad
  - type: input
    id: url
    attributes:
      label: Link to Grad Posting
      placeholder: ex. example.com/link/to/posting
    validations:
      required: true
  - type: input
    id: company_name
    attributes:
      label: Company Name
      placeholder: ex. Google
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Grad Title
      placeholder: ex. ML Software Engineer
    validations:
      required: true
  - type: input
    id: location
    attributes:
      label: Location
      description: |
        Where is the Grad located? 
        Please separate locations with a pipe "|" if there are multiple options. 
        Include Remote if remote option available.
      placeholder: San Franciso, CA | Austin, TX | Remote
    validations:
      required: true
  - type: dropdown
    id: sponsorship
    attributes:
      label: Does this opportunity offer sponsorship?
      description: |
        If the posting does not specify, or it does not fall into one of these
        categories, select "Other" then specify in parentheses at the end of
        the Opportunity Title what the sponsorship status is
      multiple: false
      options:
        - Other
        - Offers Sponsorship
        - Does Not Offer Sponsorship
        - U.S. Citizenship is Required
    validations:
      required: true
  - type: dropdown
    id: active
    attributes:
      label: Is this position currently accepting applications?
      multiple: false
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Email associated with your GitHub account (Optional)
      description: |
        If you would like to be listed as the contributor to the repository when our github action 
        commits your contribution to the repo, please provide your email. This is the only time your 
        email will be used. If left blank, your contribution will still be made, but it will be made 
        by the bot actions@github.com.
      placeholder: ex. firstLast@gmail.com
    validations:
      required: false
  - type: textarea
    id: reason
    attributes:
      label: Extra Notes (Optional)
      description: |
        Optionally, you may provide extra context/insights to our team about the internship.
        This will not be shown anywhere on the repo, but might ensure your contribution is accepted.
      placeholder: This is an exciting new company in the vr space...
    validations:
      required: false
